import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Adsence from "./components/Adsence";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="google-adsense-account" content="ca-pub-4804828229925861" />
        <Adsence pId="ca-pub-4804828229925861" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
